# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tattoo',
            old_name='photo',
            new_name='tattoo_photo',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='price',
        ),
        migrations.AddField(
            model_name='tattoo',
            name='tattoo_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='tattoo_place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='tattoo_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
